export { default as CustomerDetailsScreen } from "./CustomerDetailsScreen"
export { default as EngineerDetailsScreen } from "./EngineerDetailsScreen"
export { default as MachineDetailsScreen } from "./MachineDetailsScreen"
export { default as ProductDetailsScreen } from "./ProductDetailsScreen"
export { default as ServiceRequestDetailsScreen } from "./ServiceRequestDetailsScreen"
export { default as SpareDetailsScreen } from "./SpareDetailsScreen"
export { default as StaffDetailsScreen } from "./StaffDetailsScreen"
